### ISSUE TITLE
NerdGraph doc for developer.newrelic.com

### ISSUE THREAD

**Issue by mmfred** [newrelic/developer-toolkit#22]
This ask is similar to issue #21, but for NerdGraph

The developer website needs support in creating new content. @jthurman42 has an idea for a NerdGraph page that would help address the same central user need from multiple technologies: Terraform, the CLI, etc.

The ask: can a designated SME partner with a writer to create this page of documentation. This would entail:

- narrow down the specific use case to address. JT has thoughts on this.
- describe the problem (or need) in a few sentences or notes or bullet points
- provide any high level prerequisites - do they need an API key, or developer account or other type of access.
- provide the four or five different ways you can solve. For each one, include what to do, any particulars about doing it with each technology, and code example.

Something like this:

Do x with Terraform

Terraform is handy for doing X, because ....
This approach works best if ...
Code example

Do x with the New Relic CLI

The CLI is handy for doing X, because ....
This approach works best if ...
Code example

etc.

Time frame: would be fantastic to have a draft by 5/29.

Thank you!

**Comment by alexronquillo** [comment]
Is this something we're still looking for?

**Comment by jpvajda** [comment]
We can close this.
